name: C++ Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-test:
    name: macOS Build & Test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Install dependencies
        run: |
          brew update
          brew install cmake spdlog googletest protobuf grpc

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake -DBUILD_TESTS=ON -DBUILD_GUI=OFF ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
        shell: bash

      - name: Upload test results
        if: always() # Upload results even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results-macos
          path: ${{github.workspace}}/build/Testing
