name: C++ Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-test:
    name: ${{ matrix.os }} Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't stop all jobs if one fails
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            dependencies: |
              brew update
              brew install cmake
          - os: ubuntu-latest
            dependencies: |
              sudo apt-get update
              sudo apt-get install -y cmake build-essential libasound2-dev
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags
    
    - name: Install dependencies
      run: ${{ matrix.dependencies }}
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake -DBUILD_TESTS=ON ..
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release
    
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f "./bin/audioplayer_test" ]; then
          ./bin/audioplayer_test
        else
          find . -name "audioplayer_test" -type f -executable -exec {} \;
        fi
      shell: bash
      
    - name: Upload test results
      if: always() # Upload results even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}
        path: ${{github.workspace}}/build/Testing
